
spring:
  datasource:
    url: jdbc:h2:mem:bikeroad
    username: sa
    password:
    driver-class-name: org.h2.Driver
    properties:
      hibernate:
        show_sql: true
        format_sql: true
        default_batch_fetch_size: 100

# H2 Settings
h2:
  console:
  enabled: true
  path: /h2-console

giljabi:
  openrouteservice:
    apikey: 5b3ce3597851110001cf62483ecf789bd7cd4e4aa54423e81368768b
    directionUrl: https://api.openrouteservice.org/v2/directions/%s/json
  google:
    elevation:

      googleGetCount: 400
      apikey: AIzaSyDYPqMSYEyZP2gnt2l4UDaLLpFnQJKiPcg
      elevationUrl: https://maps.googleapis.com/maps/api/elevation/json
server:
  port: 8080
